colorScheme: mocha
defaultAppearance: dark
autoSwitchAppearance: true

enableCodeCopy: true

header:
  layout: basic

footer:
  showAppearanceSwitcher: true
  showCopyright: true

homepage:
  layout: profile
  showRecent: true
  showRecentItems: 6
  showMoreLink: true
  showMoreLinkText: "All posts"
  cardView: true
  cardViewScreenWidth: false

article:
  showDate: true
  showDateOnlyInList: false
  showDateUpdated: true
  showAuthor: true
  showBreadcrumbs: true
  showDraftLabel: true
  showEdit: false
  showHeadingAnchors: true
  showPagination: true
  showReadingTime: true
  showTableOfContents: true
  showTaxonomies: true
  showWordCount: true
  showComments: false
  sharingLinks: null

list:
  showBreadcrumbs: true
  showTableOfContents: false
  showSummary: true
  groupByYear: true
  cardView: true

taxonomy:
  showTermCount: true

seo:
  # socialImage: "img/share.jpg"
  organisationLogo: "img/logo.svg"
